---
title: "diabetes"
author: "Kellie Liu"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: spacelab
    toc: no
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(here)
library(naniar)
library(shiny)
library(shinydashboard)
```


```{r}
getwd()
```

```{r}
diabetes_2019 <- read_csv("Group Project Data/diabetes_dataset__2019.csv") %>% clean_names()
diabetes <- read_csv("Group Project Data/diabetes.csv")
heart_failture <- read_csv("Group Project Data/heart_failure_clinical_records_dataset.csv")
```

```{r}
names(diabetes)
```

```{r}
anyNA(diabetes)
```

```{r}
naniar::miss_var_summary(diabetes)
```

```{r}
diabetes <- diabetes %>% 
  mutate_if(is.character, ~str_replace(., ",", ".")) %>%
  mutate(chol_ratio = as.numeric(cholesterol/hdl_chol))
diabetes
```

```{r}
diabetes %>% 
  mutate(diabetic=ifelse(diabetes == "Diabetes", 1, 0)) %>% 
  mutate(age_category=case_when(age<=19~"teenager",
         age>=20 & age<40~"adult",
         age>=40 & age<60~"mid aged",
         age>=60 & age<80~"senior",
         age>=80~"super senior")) %>%  
  filter(age_category!="NA") %>%  
  filter(diabetic != "NA") %>% 
  count(diabetic, age_category) %>% 
  pivot_wider(names_from = diabetic,
              names_prefix = "diabetic_",
              values_from = n) %>% 
  mutate(diabetic_per = diabetic_1*100/(diabetic_1+diabetic_0)) %>% 
  ggplot(aes(x=age_category, y=diabetic_per, fill=age_category))+
  geom_col(alpha=0.6, position="dodge")+
  theme_linedraw()+
  labs(title="Diabetes Age Range",
       x="Age Group",
       y="Percent")+
  scale_x_discrete(limits=c("teenager", "adult", "mid aged", "senior", "super senior"))+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
diabetes %>% 
  mutate(diabetic=ifelse(diabetes == "Diabetes", 1, 0)) %>% 
  mutate(age_category=case_when(age<=19~"teenager",
         age>=20 & age<40~"adult",
         age>=40 & age<60~"mid aged",
         age>=60 & age<80~"senior",
         age>=80~"super senior")) %>%  
  filter(age_category!="NA") %>%  
  filter(diabetic != "NA") %>% 
  count(diabetic, age_category, gender) %>% 
  pivot_wider(names_from = diabetic,
              names_prefix = "diabetic_",
              values_from = n) %>% 
  mutate(diabetic_per = diabetic_1*100/(diabetic_1+diabetic_0)) %>% 
  ggplot(aes(x=age_category, y=diabetic_per, fill=gender))+
  geom_col(alpha=0.6, position="dodge")+
  theme_linedraw()+
  labs(title="Diabetes Age Range vs. Gender",
       x="Age Group",
       y="Percent")+
  scale_x_discrete(limits=c("teenager", "adult", "mid aged", "senior", "super senior"))+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
age_diabetes <- diabetes %>%
  mutate(diabetic=ifelse(diabetes == "Diabetes", 1, 0)) %>% 
  mutate(age_category=case_when(age<=19~"teenager",
         age>=20 & age<40~"adult",
         age>=40 & age<60~"mid aged",
         age>=60 & age<80~"senior",
         age>=80~"super senior")) %>%  
  filter(age_category!="NA")
age_diabetes
```

```{r}
age_diabetes %>%
  select(diabetes, glucose, age_category) %>% 
  group_by(diabetes, age_category) %>% 
  summarize(mean_glucose=mean(glucose)) %>% 
  ggplot(aes(x=diabetes, y=mean_glucose, fill=age_category))+
  geom_col(alpha=0.6, position="dodge")+
  theme_linedraw()+
  labs(title="Glucose Level",
       x="Diabetes",
       y="Glucose Level")+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
diabetes %>% 
  mutate(diabetic=ifelse(diabetes == "Diabetes", 1, 0)) %>% 
  mutate(chol_category=case_when(chol_ratio<=3.5~"Optimal",
         chol_ratio>=3.5 & chol_ratio<5~"Borderline High",
         age>=5~"High"))  %>%  
  filter(chol_category!="NA") %>%  
  filter(diabetic != "NA") %>% 
  count(diabetic, chol_category) %>% 
  pivot_wider(names_from = diabetic,
              names_prefix = "diabetic_",
              values_from = n) %>% 
  mutate(diabetic_per = diabetic_1*100/(diabetic_1+diabetic_0)) %>%
  ggplot(aes(x=chol_category, y=diabetic_per, fill = chol_category))+
  geom_col(alpha=0.6, position="dodge")+
  theme_linedraw()+
  labs(title="Cholesterol Ratio vs. Diabetic",
       x="Cholestrol Level",
       y="Percent")+
  scale_x_discrete(limits=c("Optimal", "Borderline High", "High"))+
  theme(plot.title = element_text(hjust = 0.5))
  
```

```{r}
diabetes %>% 
  mutate(diabetic=ifelse(diabetes == "Diabetes", 1, 0)) %>% 
  mutate(chol_category=case_when(chol_ratio<=3.5~"Optimal",
         chol_ratio>=3.5 & chol_ratio<5~"Borderline High",
         age>=5~"High"))  %>%  
  filter(chol_category!="NA") %>%  
  filter(diabetic != "NA") %>% 
  count(diabetic, chol_category, gender) %>% 
  pivot_wider(names_from = diabetic,
              names_prefix = "diabetic_",
              values_from = n) %>% 
  mutate(diabetic_per = diabetic_1*100/(diabetic_1+diabetic_0)) %>%
  ggplot(aes(x=chol_category, y=diabetic_per, fill = gender))+
  geom_col(alpha=0.6, position="dodge")+
  theme_linedraw()+
  labs(title="Diabetic Cholesterol Ratio vs. Gender",
       x="Cholestrol Level",
       y="Percent")+
  scale_x_discrete(limits=c("Optimal", "Borderline High", "High"))+
  theme(plot.title = element_text(hjust = 0.5))
  
```

```{r}
diabetes %>% 
  mutate(diabetic=ifelse(diabetes == "Diabetes", 1, 0)) %>% 
  mutate(chol_category=case_when(chol_ratio<=3.5~"Optimal",
         chol_ratio>=3.5 & chol_ratio<5~"Borderline",
         age>=5~"High"))  %>%  
  filter(chol_category!="NA") %>% 
  count(gender, chol_category) %>% 
  pivot_wider(names_from = chol_category,
              names_prefix = "chol_",
              values_from = n) %>% 
  mutate(Borderline = chol_Borderline*100/(chol_Borderline+chol_High+chol_Optimal),
         High= chol_High*100/(chol_Borderline+chol_High+chol_Optimal),
         Optimal = chol_Optimal*100/(chol_Borderline+chol_High+chol_Optimal)) %>%
  pivot_longer(-c(gender, chol_Borderline, chol_High, chol_Optimal),
               names_to = "chol_per_cat",
               values_to = "chol_per") %>% 
  ggplot(aes(x=chol_per_cat, y=chol_per, fill = gender))+
  geom_col(alpha=0.6, position="dodge")+
  theme_linedraw()+
  labs(title="Cholesterol Ratio vs. Gender",
       x="Cholestrol Level",
       y="Percent")+
  scale_x_discrete(limits=c("Optimal", "Borderline", "High"))+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}

```

```{r}
diabetes %>% 
  mutate(diabetic=ifelse(diabetes == "Diabetes", 1, 0)) %>% 
  count(diabetic, gender) %>%
  pivot_wider(names_from = diabetic,
              names_prefix = "diabetic_",
              values_from = n) %>%
  mutate(diabetic_per = diabetic_1*100/(diabetic_1+diabetic_0)) %>% 
  ggplot(aes(x=gender, y=diabetic_per, fill = gender))+
  geom_col(alpha=0.6, position="dodge")+
  theme_linedraw()+
  labs(title="Genders vs. Diabetes",
       x="Gender",
       y="Percent")+
  theme(plot.title = element_text(hjust = 0.5))
```




